meta_product_name: "H-Alt-e"
meta_title: "H-Alt-e - Change the way you live, step by step"
meta_description: "H-Alt-e is a crowdsourced app designed to help you finding the perfects alternatives for everyday products & services as D.I.Y. & featured products."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
